# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

sphinx:
  configuration: docs/source/conf.py

# Set the build OS and Python version
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

# Define the Python version and requirements file
python:
  version: 3.12
  install:
    - method: pip
      path: .
    - requirements: requirements.txt
